#!/usr/bin/env python3
"""Generate the dependency-free text catalog. TSV columns are key, uk, en, pl;
status-translations.tsv columns are original Ukrainian, en, pl. Keep trailing spaces.
"""
from pathlib import Path
import json
root = Path(__file__).resolve().parents[1]
def read(name, columns):
    rows = []
    for line in (root/'tools'/name).read_text().splitlines():
        if not line: continue
        row = [s.replace('\\n','\n') for s in line.split('\t')]
        assert len(row) == columns, (name,row)
        rows.append(row)
    assert len({row[0] for row in rows}) == len(rows), 'Duplicate key'
    return rows
ui = read('ui-translations.tsv',4)
status = read('status-translations.tsv',3)
quote = lambda s: json.dumps(s,ensure_ascii=False)
code = '''package ua.iben.recorder;

import java.util.*;

/** Generated by tools/generate_strings.py. Stored service status stays language-neutral Ukrainian. */
public final class I18n {
    private static final Map<String,String[]> UI = new LinkedHashMap<>();
    private static final List<String[]> STATUS = new ArrayList<>();
    private static volatile int language;
    private I18n() { }
    static {
'''
for row in ui: code += '        UI.put('+quote(row[0])+', new String[]{'+', '.join(map(quote,row[1:]))+'});\n'
for row in status: code += '        STATUS.add(new String[]{'+', '.join(map(quote,row))+'});\n'
code += '''        STATUS.sort((a,b) -> Integer.compare(b[0].length(), a[0].length()));
    }
    public static void use(String code) { language = "en".equals(code) ? 1 : "pl".equals(code) ? 2 : 0; }
    public static String s(String key, Object... args) {
        String[] values = UI.get(key);
        if (values == null) throw new IllegalArgumentException("Missing text: " + key);
        int index = language;
        return args.length == 0 ? values[index] : String.format(new Locale(index == 1 ? "en" : index == 2 ? "pl" : "uk"), values[index], args);
    }
    public static String uk(String key) {
        String[] values = UI.get(key);
        if (values == null) throw new IllegalArgumentException("Missing text: " + key);
        return values[0];
    }
    public static String tr(String original) {
        if (original == null) return "";
        int index = language;
        if (index == 0) return original;
        for (String[] value : UI.values()) if (value[0].equals(original)) return value[index];
        String text = original;
        for (String[] phrase : STATUS) text = text.replace(phrase[0], phrase[index]);
        return text.replaceAll("(\\\\d+) с(?=[.,;\\\\n]|$)", "$1 s");
    }
}
'''
destination = root/'app/src/main/java/ua/iben/recorder/I18n.java'
import sys
if '--check' in sys.argv:
    assert destination.read_text() == code, 'Run python3 tools/generate_strings.py after editing translations'
else:
    destination.write_text(code)
print('Generated',len(ui),'UI entries and',len(status),'status translations in 3 languages')
